version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:12.18.3
    terraform-executor:
        docker:
            - image: hashicorp/terraform:light
commands:
    install-npm-dependencies:
        steps:
            - checkout
            - restore_cache:
                  name: Restore NPM cache
                  keys:
                      - release-deps-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  name: Save NPM cache
                  key: release-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
jobs:
    lwc-app-build-and-run:
        executor: node-executor
        steps:
            - checkout
            - install-npm-dependencies
            - run:
                  name: 'Building lwc-app'
                  command: npm run build
            - run:
                  name: 'Running lwc-app'
                  command: npm run serve
                  background: true
    lwc-app-test:
        executor: node-executor
        steps:
            - checkout
            #        - run:
            #            name: Install npm dependencies
            #            command: npm install
            - install-npm-dependencies
            - run:
                  name: Run Unit tests
                  command: ./node_modules/.bin/jest
    setup-heroku-environment:
        executor: terraform-executor
        steps:
          - checkout
          - run:
              name: terraform init & plan
              command: |
                terraform init
                terraform apply --auto-approve
workflows:
    version: 2
    lwc-build-execute:
        jobs:
            - lwc-app-build-and-run
            - lwc-app-test:
                  requires:
                      - lwc-app-build-and-run
    lwc-deploy:
        jobs:
          - setup-heroku-environment:
              requires:
                - lwc-build-execute