version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:12.18.3
jobs:
    install-npm-dependencies:
        executor: node-executor
        steps:
            - checkout
            - restore_cache:
                  name: Restore NPM cache
                  keys:
                      - release-deps-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  name: Save NPM cache
                  key: release-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
    lwc-app-build-and-run:
        executor: node-executor
        steps:
            - checkout
            - install-npm-dependencies
            - run:
                  name: 'Building lwc-app'
                  command: npm run build
            - run:
                  name: 'Running lwc-app'
                  command: npm run serve
workflows:
    version: 2
    lwc-build-execute:
        jobs:
            - lwc-app-build-and-run
